### PR TITLE
Add support for MediaWiki

### PR DESCRIPTION
**Pull request by markgrovs**
This does require having Mediawiker package installed.

### CODE REVIEW

**Comment by select** [comment]
@markgrovs how does it work, I installed the package but I still cannot see the option in the pandoc popup to translate to mediawiki language?

**Comment by select** [comment]
I did that, but it did not change the options in the pandoc menu. 
Maybe I'm thinking in the wrong direction here. I'm trying to convert a markdown file to mediawiki syntax. I installed pandoc and mediawiker plugins (did not configure anything). In the markdown file I'm calling ctrl+p "pandoc" then I get a list of languages I can translate to which is missing mediawiki. Is that the way it should work?

**Comment by markgrovs** [comment]
Double check your pandoc-settings file it looks like my addition was removed back in this change: https://github.com/tbfisher/sublimetext-Pandoc/commit/f5cdc733b13d72247db37a4abeade3c24703aab1#diff-51bd1dd35c7202f7482d0399ff93f06d

**Comment by select** [comment]
Yeah the whole config file structure changed, I managed to convert to media wiki by adding a new tranformation entry in the config
```
    "transformations": {
      "Media Wiki": {
        "new-buffer": 1,
        "scope": {
          "text.html": "html",
          "text.html.markdown": "markdown"
        },
        "pandoc-arguments": ["-t", "mediawiki"]
      },
...
```
However it did not work when i was adding this to the user config.

Overall I do not get why the transformation list is so small when pandoc can convert into so many formats. For a user of this plugin that does not go all the way to find out how to add own transformations I guess this would be a bit disappointing.

**Pull request merged**
